name: ERS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Run Lint
        run: pnpm lint

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Backend
        run: pnpm --filter backend build

      - name: Run Backend Tests
        run: pnpm --filter backend test || echo "⚠️ No backend tests defined yet"

  admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Admin
        run: pnpm --filter admin build

      - name: Run Admin Tests
        run: pnpm --filter admin test || echo "⚠️ No admin tests defined yet"

  client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Expo Doctor Check
        run: pnpm --filter client expo doctor
