name: 🧹 Cleanup Supabase Preview Environment

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    name: Delete Supabase preview branch (non-blocking)

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_ORG: "Wanky Technologies Ltd"
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: 🧹 Attempt to delete Supabase preview branch
        continue-on-error: true
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          echo "Attempting to delete Supabase preview branch: preview-${BRANCH_NAME}"
          supabase db branch delete "preview-${BRANCH_NAME}" --project-ref $SUPABASE_PROJECT_REF --org $SUPABASE_ORG --no-confirm || echo "No preview branch found for this PR. Skipping cleanup."
